name: Update NHL Stats

on:
  schedule:
    # Run every hour during hockey season
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Fetch NHL stats
        run: python fetch_stats.py
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add stats.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update NHL stats" && git push)
